import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';

const features = [
  {
    title: 'AI Mock Interviews',
    desc: 'Realistic, role-specific questions generated by Gemini. Get scored on accuracy, clarity, and depth.',
    icon: '🎙️',
  },
  {
    title: 'Timed Domain Tests',
    desc: 'Pick a domain and format — MCQ, one-word, or long answer. Race the clock with a live countdown.',
    icon: '⏱️',
  },
  {
    title: 'Performance Analysis',
    desc: 'AI-powered breakdown of strengths, weaknesses, and actionable improvement suggestions.',
    icon: '📊',
  },
  {
    title: 'Interview History',
    desc: 'Every session saved to your profile. Track progress over time and revisit feedback.',
    icon: '📚',
  },
];

const Home = () => {
  const { isAuthenticated } = useSelector((s) => s.auth);

  return (
    <div className="min-h-screen">
      <nav className="flex items-center justify-between max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16">
        <Link to="/" className="flex items-center gap-2">
          <div className="h-9 w-9 rounded-xl bg-accent flex items-center justify-center font-bold text-white text-lg shadow-lg shadow-accent/30">
            A
          </div>
          <span className="text-xl font-bold text-white">
            Ace<span className="text-accent-light">Prep</span>
          </span>
        </Link>
        <div className="flex items-center gap-3">
          {isAuthenticated ? (
            <Link to="/dashboard" className="btn-primary">
              Go to Dashboard
            </Link>
          ) : (
            <>
              <Link to="/login" className="btn-ghost">
                Login
              </Link>
              <Link to="/signup" className="btn-primary">
                Get Started
              </Link>
            </>
          )}
        </div>
      </nav>

      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-32 text-center animate-slide-up">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-accent/10 border border-accent/30 text-accent-light text-sm font-medium mb-6">
          <span className="relative flex h-2 w-2">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-accent-light opacity-75"></span>
            <span className="relative inline-flex rounded-full h-2 w-2 bg-accent"></span>
          </span>
          Powered by Gemini AI
        </div>
        <h1 className="text-5xl sm:text-6xl lg:text-7xl font-extrabold text-white leading-tight tracking-tight">
          Ace Your Next
          <br />
          <span className="bg-gradient-to-r from-accent-light via-purple-400 to-pink-400 bg-clip-text text-transparent">
            Interview
          </span>
        </h1>
        <p className="mt-6 text-lg sm:text-xl text-slate-400 max-w-2xl mx-auto leading-relaxed">
          Practice with AI-generated mock interviews and timed domain tests. Get instant scoring,
          detailed feedback, and the confidence to land your dream role.
        </p>
        <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
          <Link to={isAuthenticated ? '/interview/setup' : '/signup'} className="btn-primary text-lg px-8 py-3.5">
            {isAuthenticated ? 'Start an Interview' : 'Start Practicing — Free'}
          </Link>
          <Link to="/login" className="btn-secondary text-lg px-8 py-3.5">
            I have an account
          </Link>
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          {features.map((f) => (
            <div key={f.title} className="card p-6 hover:border-accent/50 transition-colors">
              <div className="text-4xl mb-4">{f.icon}</div>
              <h3 className="text-lg font-semibold text-white mb-2">{f.title}</h3>
              <p className="text-slate-400 text-sm leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <footer className="border-t border-slate-800 py-8 text-center text-slate-500 text-sm">
        © {new Date().getFullYear()} AcePrep. Built for interview success.
      </footer>
    </div>
  );
};

export default Home;
